### ISSUE TITLE
Crash with Enigmatica 2: Expert - Extended modpack, randomly occurrs

### ISSUE THREAD

**Issue by AnzOOCH** [CleanroomMC/Cleanroom#180]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 8

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

https://mclo.gs/E40vEId
There is a chance of errors after each installation, and this problem can also occur when running on different computers after compressing and sharing the entire game directory with others.
每次安装后都有几率出错，将整个游戏目录压缩分享给其他人后，在不同的电脑中运行时也会出现这种问题。
（注意到 Caused by: java.io.IOException: 文件名、目录名或卷标语法不正确。）

### Mod List

https://mclo.gs/dXimriv

### MMC Instance Notes

not a MMC instance pack.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by jchung01** [comment]
This is an issue with Bansoukou not properly patching coremods, specifically RandomThings in this case (RandomThings adds field `VertexLighterFlat` by ASM). I think it is fixed in Bansoukou 5.x, but the way to use the mod has changed, which requires changes from the pack dev. I believe it also doesn't work properly in Cleanroom at the moment. 

The solution at the moment should be to remove/disable the duplicate RandomThings mod that doesn't have `-patched` at the end of the filename. You should do this for any other mod that has duplicate patched and non-patched versions as well.

**Comment by Rongmario** [comment]
Bansoukou issue, fixed in Bansoukou v5, and not a cleanroom issue.
