### ISSUE TITLE
传送有概率崩溃

### ISSUE THREAD

**Issue by MPCQUQ666** [CleanroomMC/Cleanroom#43]
[crash-2024-01-17_14.24.02-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13959470/crash-2024-01-17_14.24.02-client.txt)

**Comment by Ecdcaeb** [comment]
this is a bug caused by NEE(https://www.mcmod.cn/class/4423.html)
code here:https://github.com/vfyjxf/NotEnoughEnergistics/blob/1.12.2-rework/src/main/java/com/github/vfyjxf/nee/client/GuiEventHandler.java
and it is fixed  on Aug 9, 2023  :
https://github.com/vfyjxf/NotEnoughEnergistics/commit/9a13566918078d4ba65e2c27f59d58599ecda045

so, download 2.0.6, 
https://www.curseforge.com/minecraft/mc-mods/not-enough-energistics/files/4690660
